name: ie-bank-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: gringo-fe-dev  # Name of the web app in Azure

jobs: # Build & deploy
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build -- --mode development --dest dist-dev  ## This command will build the Vue.js app using .env.development variables into the dest-dev/ folder
        env:
          VUE_APP_ROOT_URL: ${{ secrets.VUE_APP_ROOT_URL }}  # Inject secret into build process
          # Add more env variables as needed
          DBUSER: ${{ secrets.DBUSER }}
          DBPASS: ${{ secrets.DBPASS }}
          DBHOST: ${{ secrets.DBHOST }}
          DBNAME: ${{ secrets.DBNAME }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist-dev/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: .
